src/Entity/Announcement.php
<?php

namespace App\Entity;

use App\Repository\AnnouncementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnouncementRepository::class)]
class Announcement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $cat_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $cat_birth = null;

    #[ORM\Column]
    private ?bool $cat_loof = null;

    #[ORM\ManyToOne(inversedBy: 'announcements')]
    private ?CatGender $cat_gender = null;

    #[ORM\ManyToOne(inversedBy: 'announcements')]
    private ?User $user = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(targetEntity: Photo::class, mappedBy: 'announcement')]
    private Collection $photos;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->creation_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCatName(): ?string
    {
        return $this->cat_name;
    }

    public function setCatName(string $cat_name): static
    {
        $this->cat_name = $cat_name;

        return $this;
    }

    public function getCatBirth(): ?\DateTimeInterface
    {
        return $this->cat_birth;
    }

    public function setCatBirth(\DateTimeInterface $cat_birth): static
    {
        $this->cat_birth = $cat_birth;

        return $this;
    }

    public function isCatLoof(): ?bool
    {
        return $this->cat_loof;
    }

    public function setCatLoof(bool $cat_loof): static
    {
        $this->cat_loof = $cat_loof;

        return $this;
    }

    public function getCatGender(): ?CatGender
    {
        return $this->cat_gender;
    }

    public function setCatGender(?CatGender $cat_gender): static
    {
        $this->cat_gender = $cat_gender;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setAnnouncement($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getAnnouncement() === $this) {
                $photo->setAnnouncement(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $is_breeder = null;

    #[ORM\Column(length: 14, nullable: true)]
    private ?string $siret = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $phone_number = null;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'user')]
    private Collection $posts;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user')]
    private Collection $comments;

    #[ORM\Column]
    private ?bool $isVerified = false;

    /**
     * @var Collection<int, Announcement>
     */
    #[ORM\OneToMany(targetEntity: Announcement::class, mappedBy: 'user')]
    private Collection $announcements;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->announcements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isBreeder(): ?bool
    {
        return $this->is_breeder;
    }

    public function setIsBreeder(bool $is_breeder): static
    {
        $this->is_breeder = $is_breeder;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }
        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }
        return $this;
    }

    public function isVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Announcement>
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): static
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements->add($announcement);
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): static
    {
        if ($this->announcements->removeElement($announcement)) {
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }
        return $this;
    }
}

src/Controller/AnnouncementController.php
<?php

namespace App\Controller;

use App\Entity\Announcement;
use App\Entity\Photo;
use App\Form\AddAnnouncementType;
use App\Repository\AnnouncementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class AnnouncementController extends AbstractController
{
    #[Route('/announcement', name: 'app_announcement')]
    public function announcement(AnnouncementRepository $announcementRepository): Response
    {
        $announcements = $announcementRepository ->findAll();

        return $this->render('announcement/index.html.twig', [
            'announcements' => $announcements,
        ]);
    }

    #[Route('/announcement-create', name: 'app_announcement_create')]
    public function announcementCreate(Request $request, EntityManagerInterface $entityManager, Security $security): Response
    {
        $user = $security->getUser();

        $announcement = new Announcement();
        $form = $this->createForm(AddAnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($user) {
                $announcement->setUser($user);
            }

            $photoFiles = $form->get('photos')->getData();
            $defaultPhoto = 'default.jpg';
            if(empty($photoFile)){
                $photo=new Photo();
                $photo->setUrl($defaultPhoto);
                $photo->setAnnouncement($announcement);
                $entityManager->persist($photo);
            }else{
                foreach ($photoFiles as $photoFile) {
                    if ($photoFile) {
                        $allowedExtensions = ['jpg', 'png', 'jpeg'];
                        $fileExtension = $photoFile->guessExtension();
        
                        if (in_array($fileExtension, $allowedExtensions)) {
                            $newFilename = uniqid() . '.' . $fileExtension;
        
                            try {
                                $photoFile->move(
                                    $this->getParameter('uploads_directory'),
                                    $newFilename
                                );
                                $photo = new Photo();
                                $photo->setUrl($newFilename);
                                $photo->setAnnouncement($announcement);
                                $entityManager->persist($photo);
                            } catch (FileException $e) {
                                $this->addFlash('error', 'Erreur lors du téléchargement de l\'image');
                            }
                        } else {
                            $this->addFlash('error', 'Format de fichier non autorisé');
                        }
                    }
                }
            }
            $entityManager->persist($announcement);
            $entityManager->flush();

            return $this->redirectToRoute('app_announcement');
        }
        return $this->render('announcement/index-create.html.twig', [
            'addAnnouncementForm' => $form->createView(),
        ]);
    }

    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/announcement/{id}/delete', name: 'announcement_delete', methods:"POST")]
    public function delete(Announcement $announcement, Request $request): RedirectResponse
    {
        if ($announcement->getUser() === $this->getUser()) {
            foreach ($announcement->getPhotos() as $photo) {
                $this->entityManager->remove($photo);
            }
            $this->entityManager->remove($announcement);
            $this->entityManager->flush();

            $this->addFlash('success', 'Annonce supprimée avec succès.');
        }

        // Rediriger vers la liste des annonces
        return $this->redirectToRoute('app_announcement');
    }

}

templates/announcement/index-create.html.twig
{% extends 'base.html.twig' %}

{% block title %}FluffyRagdolls - Announce création{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/announcement.css') }}"> 
{% endblock %}

{% block body %}
    <main>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-light mb-4 custom-shadow">
                    <div class="card-body">
                        {{ form_start(addAnnouncementForm) }}
                            <div class="box">
                                {{ form_row (addAnnouncementForm.cat_name) }}
                            </div>
                            <div class="box">
                                {{ form_row (addAnnouncementForm.cat_birth) }}
                            </div>
                            <div class="box">
                                {{ form_row (addAnnouncementForm.cat_loof) }}
                            </div>
                            <div class="box">
                                {{ form_row (addAnnouncementForm.cat_gender) }}
                            </div>
                            {{ form_row (addAnnouncementForm.description) }}
                            <br>
                            {{ form_row (addAnnouncementForm.photos) }}
                            <br>
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-danger">Créer l'annonce</button>
                            </div>
                        {{ form_end(addAnnouncementForm) }}
                    </div>
                </div>
            </div>
        </div>
    </main>
    {{ form_errors(addAnnouncementForm) }}
{% endblock %}

templates/announcement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FluffyRagdolls - Toutes les annonces{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/announcement.css') }}"> 
{% endblock %}

{% block body %}
    <main>
        <div class="col">
            {% if app.user is null %}
                <div class="no-account-announcement">
                    <img src="{{ asset('assets/img/no-account.jpeg') }}">
                    <p>Vous devez être connecté pour accéder à cette page.</p>
                </div>
            {% else %}
                {% if announcements is not empty %}
                    {% for announcement in announcements %}
                        <div class="col-md-12">
                            <div class="col d-flex content-announcement">
                                <div class="card-phone-announcement">
                                    <div class="photo-announcement">
                                        {% for photo in announcement.photos %}
                                            <img class="photo-announcement" src="{{ asset('uploads/' ~ photo.url) }}" alt="Image de l'annonce">
                                        {% endfor %}
                                        {% if announcement.catGender.id  == '2'  %}
                                            <img class="gender-announcement" src="{{ asset('assets/img/female-sign.png') }}" alt="Chat femelle">
                                        {% else %}
                                            <img class="gender-announcement" src="{{ asset('assets/img/male-sign.png') }}" alt="Chat male">
                                        {% endif %}
                                    </div>
                                    <div class="card-announcement">
                                        <table >
                                            <tbody>
                                                <tr>
                                                    <td><img class="tag-announcement" src="{{ asset('assets/img/tag-solid.png') }}" alt="Nom"></td>
                                                    <td>{{ announcement.catName }}</td>
                                                </tr>
                                                <tr>
                                                    <td><img class="tag-announcement" src="{{ asset('assets/img/cake-solid.png') }}" alt="Date de naissance"></td>
                                                    <td>{{ announcement.catBirth|date('d-m-Y') }}</td>
                                                </tr>
                                                <tr>
                                                    <td><img class="tag-announcement" src="{{ asset('assets/img/map-solid.png') }}" alt="Ville"></td>
                                                    <td>{{ announcement.user.city }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="d-flex phone-announcement">
                                        {% if announcement.user and announcement.user.phoneNumber %}
                                            <p id="phone-display-{{ loop.index }}">••••••••••</p>
                                        {% else %}
                                            <p>Numéro de téléphone non disponible.</p>
                                        {% endif %}
                                        <button class="btn btn-danger btn-phone" onclick="showPhoneNumber('{{ announcement.user.phoneNumber }}', {{ loop.index }})">
                                            <img class="tag-phone" src="{{ asset('assets/img/phone-solid.png') }}" alt="Bouton n°tel">
                                        </button>
                                    </div>
                                </div>
                                <p class="description-announcement">{{ announcement.description }}</p>
                                {% if app.user == announcement.user %}
                                    <form action="{{ path('announcement_delete', {'id': announcement.id}) }}" method="POST" style="display:inline;" id="delete-form-{{ announcement.id }}">
                                        <button type="button" class="btn btn-outline-danger btn-delete-announcement" onclick="confirmDelete({{ announcement.id }})">❌</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    {% endfor %}
                {% else %}
                    <p>Aucune annonce trouvée.</p>
                {% endif %}
            {% if app.user.isBreeder %}
                <button class="btn btn-danger btn-announcement"><a class="" href="/announcement-create">Créer une annonce</a></button>
            {% endif %}
        </div>
    </main>

    <footer>
        <p>© Agathe Dupuis 2024</p>
    </footer>

    <script>
        function showPhoneNumber(phoneNumber, index) {
            const phoneDisplay = document.getElementById('phone-display-' + index);
            if (phoneDisplay.textContent === "••••••••••") {
                phoneDisplay.textContent = phoneNumber;
            } else {
                phoneDisplay.textContent = "••••••••••";
            }
        }

        function confirmDelete(announcementId) {
        // Demande de confirmation avant de soumettre le formulaire
        if (confirm("Êtes-vous sûr de vouloir supprimer cette annonce ?")) {
            // Soumettre le formulaire si l'utilisateur confirme
            document.getElementById('delete-form-' + announcementId).submit();
        }
    }
    </script>
{% endif %}
{% endblock %}